### ISSUE TITLE
Dropbox link missing/invalid

### ISSUE THREAD

**Issue by moritzschaefer** [sanjanalab/GUIDES#1]
The Dropbox link for the static data referenced in the README is invalid. In the install.sh script the link is missing and marked as a TODO.
Is the Dropbox link public and if yes, could you add it to the README?

**Comment by joshim5** [comment]
Thanks for reporting this. I've updated the README and install.sh.
The data folder can be found here: https://www.dropbox.com/s/sp59h2m6vjrsr1c/GUIDES_DATA.zip?dl=0
