### ISSUE TITLE
missing 'pd_by_tissue_normalized.p' file

### ISSUE THREAD

**Issue by yech1990** [sanjanalab/GUIDES#2]
- Would you please sent me a demo of `pd_by_tissue_normalized.p` file?
- How to disable tissue annotation on the system?
- How to generate reference data of other species?

**Comment by joshim5** [comment]
The `pd_by_tissue_normalized.p` file can be found in our Dropbox, as described in the README: https://www.dropbox.com/s/sp59h2m6vjrsr1c/GUIDES_DATA.zip?dl=0

The system supports disabling the use of gene expression. Simply uncheck "Use expression data to pick exons?" on the front-end tool.

Generating reference data of other species is currently not supported by GUIDES, as there are several existing open-source tools that are available for this task.
