### ISSUE TITLE
NBPF24 gene always included when uploading txt file

### ISSUE THREAD

**Issue by MaWeffm** [sanjanalab/GUIDES#3]
Hi, great tool!

I noticed that, whatever gene names are in my uploaded list, the tool always includes a gene called NBPF24. I suppose this is not meant to happen on purpose.

Best, Martin

**Comment by joshim5** [comment]
Hi Martin,

Thanks for reporting your issue here. This can happen if you have a blank line in your uploaded list. This empty string is being mapped to NBPF24.

Hope this helps!

Best,
Josh
